#!/bin/sh -efu

. gb-sh-functions

fail_if_result_not_needed

fail()
{
	stamp_echo >&2 "[$arch] arepo save FAILED"
	exit 1
}

for arch in ${GB_AREPO_ARCH-}; do
	[ -s plan/arepo-add-$arch -o -s plan/arepo-rm-$arch ] || continue
	(umask 002; mkdir -p arepo/$arch/base) || fail
	rsync -rlt --exclude='ds.*' "$GB_AREPO_DIR/$arch/base/" arepo/$arch/base/ || fail
done

#stamp_echo >&2 'arepo save OK'
